#pragma once

#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_COMBINED
#define PMW33XX_CS_PIN GP5
#define PMW33XX_LIFTOFF_DISTANCE 0x03

#define POINTING_DEVICE_COMBINED
#define POINTING_DEVICE_ROTATION_180
#define ROTATIONAL_TRANSFORM_ANGLE  10 // TESTING RIGHT SHIFTED FROM -35 TO -45 TO TEST LEFT
#define POINTING_DEVICE_INVERT_Y_RIGHT
#define POINTING_DEVICE_INVERT_Y
#define POINTING_DEVICE_INVERT_X
#define SPI_DRIVER SPID0
#define SPI_MOSI_PIN GP3
#define SPI_MISO_PIN GP4
#define SPI_SCK_PIN GP2
#define PMW33XX_CS_PIN GP5
#define POINTING_DEVICE_TASK_THROTTLE_MS 1
//#define PMW33XX_LIFTOFF_DISTANCE 0x02

#define SPLIT_TRANSACTION_IDS_KB RPC_ID_KB_CONFIG_SYNC

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
// only required if not setting mouse layer elsewhere
// #define AUTO_MOUSE_DEFAULT_LAYER 3
//
// #define DYNAMIC_KEYMAP_LAYER_COUNT 5

#define POINTING_DEVICE_DEBUG
